set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'off'
set -g mouse on

set -g status-left-length 100
set -g status-left "#[bold,fg=black] #S #[default] | "
set -g status-right "#[fg=black]%H:%M %d-%b-%y"

bind C-j display-popup -E "\
PROJECTS_DIR='/Users/pedrofrigo/Desktop/Projects'; \
selected=\$( { find \"\$PROJECTS_DIR\" -maxdepth 3 -type d -path '*/Repos/*'; echo \"\$HOME/dotfiles\"; echo \"\$HOME/Downloads\"; } | fzf --reverse --header='select project'); \
[ -z \"\$selected\" ] && exit 0; \
repo=\$(basename \"\$selected\"); \
session_name=\$(echo \"\$repo\" | tr '. ' '__'); \
if ! tmux has-session -t=\"\$session_name\" 2>/dev/null; then \
  tmux new-session -d -s \"\$session_name\" -c \"\$selected\" -n dev; \
  tmux send-keys -t \"\$session_name:dev.0\" 'nvim .' C-m; \
  tmux split-window -h -p 35 -t \"\$session_name:dev\" -c \"\$selected\"; \
  tmux select-pane -t \"\$session_name:dev.0\"; \
  tmux new-window -t \"\$session_name\" -n term -c \"\$selected\"; \
  tmux split-window -t \"\$session_name:term\" -c \"\$selected\"; \
  tmux split-window -t \"\$session_name:term\" -c \"\$selected\"; \
  tmux split-window -t \"\$session_name:term\" -c \"\$selected\"; \
  tmux select-layout -t \"\$session_name:term\" tiled; \
  tmux select-pane -t \"\$session_name:term.0\"; \
  tmux select-window -t \"\$session_name:dev\"; \
fi; \
tmux switch-client -t \"\$session_name\""

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h select-pane -L
bind C-k select-pane -U
bind C-l select-pane -R
bind C-o switch-client -l
bind C-n next-window
run '~/.tmux/plugins/tpm/tpm'
